project:
  type: website
  title: "Sri Aurobindo and The Mother"

website:
  page-navigation: true
  sidebar:
    collapse-level: 1
    border: true
    foreground: "primary"
    contents: auto

format:
  html:
    theme: 
      light: [cosmo]
    fontsize: 20px
    toc: true
